apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-fmgk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-fmgk
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-fmgk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-fmgk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-fmgk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-jehy-tenant/appstudio/devfile-sample-python-basic-fmgk@sha256:51581ad7bb923c5dadde4a22cc3419a4901e25b27e4a90dadbe4f37bbf9cce8e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
