apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-vswm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-vswm
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-vswm
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-vswm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-vswm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-jehy-tenant/appstudio/dc-metro-map-vswm@sha256:24e69a07d01a577a2b851556a18e8575343513bad08f01d92a0a8b945bc6254d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
